todo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

from engine.views import HomeView, LoginView, SignUpView, LogoutView, ToDoListDisplayView, CompleteTaskAPIView, \
    AddTaskFormView, AssignTaskFormView, AcceptTaskAPIView, ActivateView, TaskDetailView, CompleteTaskView, \
    AcceptTaskView, DeleteTaskView, DashboardView, GoalsView, GoalsDetailView, AddUnitView, AddGoalView, \
    AddResourceView, AddCommentView, UpdateTaskGoodView, UpdateTaskHelpView, UpdateTaskTroubleView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'todo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^tasks/$', ToDoListDisplayView.as_view(), name='tasks'),
    url(r'^new-task/$', AddTaskFormView.as_view(), name='add-task'),
    url(r'^assign-task/(?P<pk>\d+)/', AssignTaskFormView.as_view(), name='assign-task'),
    url(r'^details/(?P<pk>\d+)/$', TaskDetailView.as_view(), name='task-detail'),
    # url(r'^complete-task/(?P<pk>\d+)/$', CompleteTaskAPIView.as_view(), name='complete-task-api'),
    # url(r'^accept-task/(?P<pk>\d+)/$', AcceptTaskAPIView.as_view(), name='accept-task-api'),
    url(r'^complete-task/(?P<pk>\d+)/$', CompleteTaskView, name='complete-task'),


    url(r'^update-task-good/(?P<pk>\d+)/$', UpdateTaskGoodView, name='update-task-good'),
    url(r'^update-task-help/(?P<pk>\d+)/$', UpdateTaskHelpView, name='update-task-help'),
    url(r'^update-task-trouble/(?P<pk>\d+)/$', UpdateTaskTroubleView, name='update-task-trouble'),

    url(r'^accept-task/(?P<pk>\d+)/$', AcceptTaskView, name='accept-task'),
    url(r'^delete-task/(?P<pk>\d+)/$', DeleteTaskView, name='delete-task'),
    url(r'^dashboard/$', DashboardView.as_view(), name='dashboard'),
    url(r'^dashboard/unit/add/$', AddUnitView.as_view(), name='add-unit'),
    url(r'^dashboard/goals/(?P<pk>\d+)/$', GoalsView.as_view(), name='goals'),
    url(r'^dashboard/goals/add/(?P<pk>\d+)/$', AddGoalView.as_view(), name='goals-add'),
    url(r'^dashboard/goals/tasks/(?P<pk>\d+)/$', GoalsDetailView.as_view(), name='goals-detail'),
    url(r'^task/(?P<pk>\d+)/add-resource/$', AddResourceView.as_view(), name='add-resource' ),
    url(r'^task/(?P<pk>\d+)/add-comment/$', AddCommentView.as_view(), name='add-comment' ),

    url(r'^signup/$', SignUpView.as_view(), name='signup'),
    url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^activate/(?P<token>[-\w]+)/$', ActivateView.as_view(), name='activate'),

)

engine/models.py
from django.db import models
from django.contrib.auth.models import User
import string
import random


PROJECT_STATUS = (
    ('good', 'I\'m in good shape'),
    ('help', 'I need help'),
    ('trouble', 'I am in trouble'),
)


class BaseModel(models.Model):

    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


class UserProfile(BaseModel):
    user = models.OneToOneField(User, related_name='profile')
    is_admin = models.BooleanField(default=False)

    auth_token = models.TextField(blank=True, default=u'')

    def __unicode__(self):
        return u'Profile for %s' % self.user

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        if not self.auth_token:
            self.auth_token = ''.join(random.choice(
                string.ascii_uppercase + string.ascii_lowercase + string.digits
            ) for _ in range(32))

        return super(UserProfile, self).save(force_insert, force_update, using, update_fields)


class ToDoList(BaseModel):
    owner = models.ForeignKey(User)

    def __str__(self):
        return u'To-Do List for %s' % self.owner.email



class BusinessUnit(BaseModel):
    name = models.CharField(max_length=300)
    manager = models.ForeignKey(User, null=True, blank=True)

    def __str__(self):
        return self.name


class Goal(BaseModel):
    name = models.CharField(max_length=300)
    owner = models.ForeignKey(User, null=True, blank=True)
    business_unit = models.ForeignKey(BusinessUnit, related_name='goals')

    def __str__(self):
        return self.name


class ToDoItem(BaseModel):
    list = models.ForeignKey(ToDoList)
    creator = models.ForeignKey(User)
    title = models.CharField(blank=False, max_length=100)
    description = models.TextField(blank=True)
    complete = models.BooleanField(default=False)
    from_admin = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now_add=True)
    goal = models.ForeignKey(Goal, related_name='tasks')
    status = models.CharField(max_length=30, choices=PROJECT_STATUS, default='good')

    def __str__(self):
        return self.title


class Resource(BaseModel):
    name = models.CharField(max_length=300)
    link = models.CharField(max_length=300)
    task = models.ForeignKey(ToDoItem)
    creator = models.ForeignKey(User)

    def __str__(self):
        return self.name


class Comment(BaseModel):
    text = models.TextField(max_length=1000)
    author = models.ForeignKey(User)
    task = models.ForeignKey(ToDoItem)

    def __str__(self):
        return u'Comment by %s' % self.author

engine/views.py
from django.views.generic import TemplateView, FormView, View
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import RequestContext
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives

from django.conf import settings


from .models import UserProfile, ToDoList, ToDoItem, BusinessUnit, Goal, Resource, Comment
from .forms import AddTaskForm, AssignTaskForm, LoginForm, SignUpForm, ActivateForm, ProjectStatusForm, \
    AddBizUnitForm, AddGoalForm, AddResourceForm, AddCommentForm


# Create your views here.

class SignUpView(FormView):
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = '/tasks/'

    def form_valid(self, form):

        # Get data from form
        email = form.cleaned_data.get('email').lower()
        username = email[:30] # Limit to 30 chars
        first_name = form.cleaned_data.get('first_name')
        last_name = form.cleaned_data.get('last_name')
        password = form.cleaned_data.get('password')

        # Create a new user object
        user = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)

        # Authenticate the user
        user = authenticate(username=username, password=password)

        # Create user profile
        profile = UserProfile.objects.create(
            user=user,
        )

        # Create a new task list for the user
        list = ToDoList.objects.create(owner=user)

        # Log the user in
        login(self.request, user)

        return super(SignUpView, self).form_valid(form)


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'login.html'
    success_url = ''

    def get_context_data(self, **kwargs):

        context = super(LoginView, self).get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next')

        return context

    def form_valid(self, form):

        username = User.objects.get(email=form.cleaned_data.get('email')).username
        user = authenticate(username=username, password=form.cleaned_data.get('password'))

        if user:
            login(self.request, user)

        if 'next' in self.request.GET:
            self.success_url = self.request.GET.get('next')
        else:
            self.success_url = '/tasks/'

        return super(LoginView, self).form_valid(form)


class LogoutView(View):

    def get(self, request):
        logout(request)

        return redirect('home')


class ActivateView(FormView):
    template_name = 'activate.html'
    form_class = ActivateForm
    success_url = '/tasks/'

    def dispatch(self, request, *args, **kwargs):

        token = kwargs.get('token')
        pk = kwargs.get('pk')

        try:
            user = User.objects.get(profile__auth_token=token)
        except User.DoesNotExist:
            return redirect('home')

        kwargs['user'] = user

        return super(ActivateView, self).dispatch(request, *args, **kwargs)


    def form_valid(self, form):

        user = User.objects.get(profile__auth_token=self.kwargs.get('token'))

        user.username = user.email[:30]
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.set_password(form.cleaned_data['password'])
        user.save()

        # Authenticate the user
        user = authenticate(username=user.username, password=form.cleaned_data['password'])

        # Log the user in
        login(self.request, user)

        return super(ActivateView, self).form_valid(form)


class HomeView(TemplateView):
    template_name = 'engine/home.html'


class ToDoListDisplayView(TemplateView):
    template_name = 'engine/tasks.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):

        return super(ToDoListDisplayView, self).dispatch(request, *args, **kwargs)


    def get_context_data(self, **kwargs):

        list = ToDoList.objects.get(owner=self.request.user)

        try:
            tasks = ToDoItem.objects.filter(list=list, complete=False)
        except ToDoItem.DoesNotExist:
            tasks = None

        try:
            completed_tasks = ToDoItem.objects.filter(list=list, complete=True)
        except ToDoItem.DoesNotExist:
            completed_tasks = None

        return {
            'tasks': tasks,
            'completed_tasks': completed_tasks,
        }


class AddTaskFormView(FormView):
    form_class = AddTaskForm
    template_name = 'engine/new_task.html'
    success_url = '/tasks/'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):

        return super(AddTaskFormView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):

        task = ToDoItem.objects.create(
            list = ToDoList.objects.get(owner=self.request.user),
            title = form.cleaned_data.get('title'),
            description = form.cleaned_data.get('description'),
            creator = self.request.user,
        )

        return super(AddTaskFormView, self).form_valid(form)


class AssignTaskFormView(FormView):
    form_class = AssignTaskForm
    template_name = 'engine/assign_task.html'
    success_url = '/dashboard/'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):

        pk = kwargs.get('pk')
        kwargs['goal'] = Goal.objects.get(pk=pk)

        return super(AssignTaskFormView, self).dispatch(request, *args, **kwargs)


    def get(self, *args, **kwargs):

        context = self.get_context_data(**kwargs)
        context['form'] = self.get_form(form_class=self.get_form_class())
        context['goal'] = kwargs.get('goal')

        return self.render_to_response(context)


    def post(self, request, *args, **kwargs):

        form = self.get_form_class()(request.POST)

        if not form.is_valid():
            context = self.get_context_data(**kwargs)
            context['form'] = form
            context['goal'] = kwargs.get('goal')

            return self.render_to_response(context=context)

        return self.form_valid(form=form)


    def form_valid(self, form):

        try:
            assignee = User.objects.get(email=form.cleaned_data.get('assignee'))
            html_message = '<p>A new task item has been assigned to you. You\'d better <a href="http://'+settings.SITE_URL+'/tasks">go do it now</a>!</p>'
        except User.DoesNotExist:
            assignee = User.objects.create_user(username=form.cleaned_data.get('assignee').lower()[:30], email=form.cleaned_data.get('assignee').lower())
            list = ToDoList.objects.create(owner=assignee)
            profile = UserProfile.objects.create(user=assignee)
            html_message = '<p>A new task item has been assigned to you. You\'d better <a href="http://'+settings.SITE_URL+'/activate/'+assignee.profile.auth_token+'">go do it now</a>!</p>'

        task = ToDoItem.objects.create(
            list = ToDoList.objects.get(owner=assignee.pk),
            title = form.cleaned_data.get('title'),
            from_admin = True,
            description = form.cleaned_data.get('description'),
            creator = self.request.user,
            goal = Goal.objects.get(pk=self.kwargs.get('pk')),
        )

        # Send the email
        subject = u"New ToDo Assigned to You"
        message = u"A new task has been assigned to you. You'd better go do it!"
        html_message = html_message
        sender = self.request.user.email
        recipient = assignee.email

        subject, from_email, to = subject, sender, recipient
        text_content = message
        html_content = html_message
        msg = EmailMultiAlternatives(subject, text_content, from_email, [to])
        msg.attach_alternative(html_content, "text/html")
        msg.send()


        # self.success_url = '/dashboard/goals/tasks/%s/' % task.goal.id


        return super(AssignTaskFormView, self).form_valid(form)



# class AssignTaskFormView(TemplateView):
#     template_name = 'engine/assign_task.html'
#     http_method_names = ['get', 'post', ]
#
#     def dispatch(self, request, *args, **kwargs):
#
#         # Here we are somehow buildilng the list of people
#         people = (('', '--------'), )
#         for p in User.objects.all().order_by('last_name'):
#             people = people + ((p.id, p.email), )
#
#         self.assignees = people
#
#         return super(AssignTaskFormView, self).dispatch(request, *args, **kwargs)
#
#
#     def get(self, request, *args, **kwargs):
#
#         context = self.get_context_data(**kwargs)
#         context['form'] = AssignTaskForm(assignees=self.assignees)
#
#         return self.render_to_response(context)
#
#
#     def post(self, requets, *args, **kwargs):
#
#         form = AssignTaskForm(assignees=self.assignees)
#
#         if form.is_valid():
#             # Create the task
#
#             if form.cleaned_data.get('assignee', None):
#                 try:
#                     assignee = User.objects.get(pk=form.cleaned_data.get('assignee'))
#                 except (User.DoesNotExist, User.MultipleObjectsReturned):
#                     assignee = None
#             else:
#                 assignee = None
#
#
#             task = ToDoItem.objects.create(
#                 list = ToDoList.objects.get(owner__pk=assignee.user.pk),
#                 title = form.cleaned_data.get('title'),
#                 from_admin = True,
#                 description = form.cleaned_data.get('description'),
#             )
#
#         return redirect('tasks')


class CompleteTaskAPIView(View):
    http_method_names = ['post', ]

    def post(self, request, *args, **kwargs):

        task_id = request.POST.get('pk')

templates/engine/_navigation.html
{% load static %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="#">Accomplished</a>-->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'dashboard' %}">Overview</a></li>


      </ul>
      {% if user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
          <li><a>Hello, {{ user.first_name }}</a></li>
          <li><a href="{% url 'tasks' %}">My Tasks</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
      </ul>
      {% endif %}
    </div><!--/.nav-collapse -->
  </div>
</div>

templates/engine/add_business_unit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    {% include 'engine/_navigation.html' %}

    <div class="container">
        <div class="content-container">
            <div class="row">
                <div class="col-xs-12">

                    <h2>Add Business Unit</h2>

                     <form role="form" method="post" action="">

                            {% csrf_token %}

                            {{ form.errors.name }}
                            {{ form.name }}

                            <div>&nbsp;</div>

                            <button type="submit" class="btn btn-lg btn-primary">Add Business Unit</button>

                     </form>

                    <div>&nbsp;</div>
                    <a href="{% url 'dashboard' %}">Back to Dashboard</a>


                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/engine/add_comment.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

{% include 'engine/_navigation.html' %}

    <div class="container">

        <div class="content-container">

            <h2>Add Comment</h2>


            <form role="form" method="post" action="">

                {% csrf_token %}

                <div class="form-group">

                    <label for="title">Comment</label>
                    {{ form.text.errors }}
                    {{ form.text }}

                </div>

                <button type="submit" class="btn btn-lg btn-primary">Submit</button>

            </form>

        </div>

    </div>


{% endblock %}

templates/engine/add_goal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


    {% include 'engine/_navigation.html' %}

    <div class="container">
        <div class="content-container">
            <div class="row">
                <div class="col-xs-12">

                    <h2>Add {{ unit }} Goal</h2>

                     <form role="form" method="post" action="">

                            {% csrf_token %}

                            {{ form.errors.name }}
                            {{ form.name }}

                            <div>&nbsp;</div>

                            <button type="submit" class="btn btn-lg btn-primary">Add {{ unit }} Goal</button>
                            <div>&nbsp;</div>
                            <a href="{% url 'dashboard' %}">Cancel</a>

                     </form>


                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/engine/add_resource.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

{% include 'engine/_navigation.html' %}

    <div class="container">

        <div class="content-container">

            <h2>Add a Resource</h2>


            <form role="form" method="post" action="">

                {% csrf_token %}

                <div class="form-group">

                    <label for="title">Title</label>
                    {{ form.name.errors }}
                    {{ form.name }}

                    <div>&nbsp;</div>

                    <label for="description">Description</label>
                    {{ form.link.errors }}
                    {{ form.link }}

                    <div>&nbsp;</div>

                </div>

                <button type="submit" class="btn btn-lg btn-primary">Submit</button>

            </form>

        </div>

    </div>


{% endblock %}

templates/engine/assign_task.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

{% include 'engine/_navigation.html' %}

    <div class="container">

        <div class="content-container">

            <h2>Assign a Task</h2>
            <p class="lead">This will be added to your task list for your goal to <b>{{ goal }}</b>.</p>

            <form role="form" method="post" action="">

                {% csrf_token %}

                <div class="form-group">

                    <label for="title">Title</label>
                    {{ form.title.errors }}
                    {{ form.title }}

                    <div>&nbsp;</div>

                    <label for="description">Description</label>
                    {{ form.description.errors }}
                    {{ form.description }}

                    <div>&nbsp;</div>

                    <label for="assignee">Assign to User</label>
                    {{ form.assignee.errors }}
                    {{ form.assignee }}


                    <div>&nbsp;</div>


                </div>

                <button type="submit" class="btn btn-lg btn-primary">Submit</button>
                <div>&nbsp;</div>
                <a href="{% url 'dashboard' %}">Cancel</a>

            </form>

        </div>

    </div>


{% endblock %}

templates/engine/biz_unit_goals.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    {% include 'engine/_navigation.html' %}

    <div class="container">
        <div class="content-container">
            <div class="row">
                <div class="col-xs-12">

                    <h2>Goals for {{ unit }}</h2>

                    <ul class="list-group">
                    {% for g in goals %}
                        <li class="list-group-item"><a href="">{{ g }}</a></li>
                    {% empty %}
                        <p>You haven't entered any goals for this business unit.</p>
                    {% endfor %}
                    </ul>

                    <a href="" class="btn btn-block btn-lg btn-primary">Add New Goal</a>

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}


{% endblock %}

templates/engine/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'engine/_navigation.html' %}

    <div class="container">
        <div class="content-container">
            <div class="row">
                <div class="col-xs-12">

                    <h2>Overview</h2>


                    {% for unit in biz_units %}
                    <div class="panel panel-default">
                      <!-- Default panel contents -->
                      <div class="panel-heading clearfix">
                          <span class="pull-left">
                              <b>{{ unit }}</b>
                          </span>
                          <span class="pull-right">
                               <small><a href="{% url 'goals-add' unit.id %}">New {{ unit }} Goal</a></small>
                          </span>
                      </div>


                      <!-- List group -->

                      {% for goal in unit.goals.all %}
                        <h4 style="padding: 20px 14px 20px 14px;">{{ goal }}</h4>
                          <ul class="list-group">
                          {% for task in goal.tasks.all %}
                              <li class="list-group-item clearfix">
                                <span class="pull-left">
                                    <a href="{% url 'task-detail' task.id %}">{{ task }}</a>
                                </span>

                                <span class="pull-right">
                                    <small>{{ task.list.owner.get_full_name }}</small>&nbsp;&nbsp;&nbsp;<span class="{{ task.status }} pull-right">&nbsp;</span>
                                </span>

                              </li>


                          {% endfor %}
                            <li class="list-group-item"><a class="btn btn-primary" href="{% url 'assign-task' goal.id %}">Add task</a></li>
                          </ul>


                        {% empty %}
                        <ul class="list-group">
                        <li class="list-group-item">You haven't listed any goals for this business unit.</li>
                        </ul>
                      {% endfor %}

                    </div>

                    <div>&nbsp;</div>

                    {% endfor %}

                    <a href="{% url 'add-unit' %}" class="btn btn-lg btn-primary">Add new Business Unit</a>

                    <div>&nbsp;</div>
                    <div>&nbsp;</div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}


{% endblock %}

templates/engine/goals.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'engine/_navigation.html' %}

    <div class="container">
        <div class="content-container">
            <div class="row">
                <div class="col-xs-12">

                    <h2>Goals for {{ unit }}</h2>

                    <ul class="list-group">
                    {% for goal in goals %}
                        <li class="list-group-item"><a href="{% url 'goals-detail' goal.id  %}">{{ goal }}</a></li>
                    {% empty %}
                        <p class="lead">You haven't entered any goals for this business unit.</p>
                    {% endfor %}
                    </ul>

                    <a href="{% url 'goals-add' unit.id %}" class="btn btn-lg btn-primary">Add New {{ unit }} Goal</a>
                    <div>&nbsp;</div>
                    <a href="{% url 'dashboard' %}">Back to Dashboard</a>

                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block extra_js %}


{% endblock %}

templates/engine/task-detail.html
{% extends 'base.html'%}
{% load static %}

{% block content %}

    {% include 'engine/_navigation.html' %}

    <div class="container">

      <div class="content-container">



        <div class="task-header clearfix">

                <h1>{{ task }}</h1>

                {% if user == task.list.owner %}

                    <div>&nbsp;</div>

                        <button id="good" {% if task.status == 'good' %}class="btn btn-success"{% else %}class="btn btn-default"{% endif %} data-task-id="{{ task.id }}">I'm Good</button>
                        <button id="help" {% if task.status == 'help' %}class="btn btn-warning"{% else %}class="btn btn-default"{% endif %} data-task-id="{{ task.id }}">I need help</button>
                        <button id="trouble" {% if task.status == 'trouble' %}class="btn btn-danger"{% else %}class="btn btn-default"{% endif %} data-task-id="{{ task.id }}">I'm in trouble</button>
                    </div>
                    <div>&nbsp;</div>


                {% endif %}


                <a href="{% url 'dashboard' %}">Back to Overview</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="{% url 'tasks' %}">View My Tasks</a>
                <hr />


                <p>
                    <b>Created by:</b> {{ creator }} on {{ task.created }}<b><br />
                    Assigned to:</b>&nbsp;{{ task.list.owner.get_full_name }}<br />
                    <b>Due on:</b>
                </p>


        </div>


        <h4>Description:</h4>
        {% if description %}
        <p>{{ description }}</p>
        {% else %}
        <em>None provided</em>
        {% endif %}


        <hr />

        <h4>Comments:</h4>
        {% if comments %}
        <ul>
        {% for comment in comments %}
            <blockquote>{{ comment.text }}<br /><small><b>{{ comment.author.get_full_name }}</b> on {{ comment.created }}</small></blockquote>

        {% endfor %}
        </ul>
        {% endif %}
        <a href="{% url 'add-comment' task.id %}">Add Comment</a>
        <hr />

        <h4>Resources:</h4>
        {% if resources %}
        <ul>
        {% for resource in resources %}
            <li><a href="{{ resource.link }}" target="_blank">{{ resource }}</a></li>
        {% endfor %}
        </ul>
        {% endif %}

        <a href="{% url 'add-resource' task.id %}">Add Resource</a>
        <hr />


        {% if user == task.list.owner %}
        <a href="{% url 'complete-task' task.id %}" class="btn btn-lg btn-primary">Complete Task</a>
        {% endif %}


        <div>&nbsp;</div>
        <div>&nbsp;</div>
      </div>

    </div><!-- /.container -->



{% endblock %}


{% block extra_js %}

{#    <script>#}
{##}
{#        $( "select#id_status" ).change(function() {#}
{##}
{##}
{##}
{#            var pk = {{ task.id }};#}
{#            var status = $(this).val();#}
{##}
{#            var url = '/task/update/' + pk + '/' + status + '/';#}
{##}
{#            //alert(status);#}
{#            //alert(url);#}
{##}
{##}
{#            $.ajax({#}
{#                type: 'POST',#}
{#                url: url,#}
{#                dataType: 'json',#}
{#                async: true,#}
{#                data: {#}
{#                    csrfmiddlewaretoken: '{{ csrf_token }}',#}
{#                    pk: pk,#}
{#                    status: status,#}
{#                },#}
{#                success: function(json) {#}
{##}
{#                }#}
{#            });#}
{##}
{##}
{#        });#}
{##}
{#    </script>#}

    <script>


        $('button#good').click(function() {

            var pk = $(this).data('task-id');
            var url = '/update-task-good/' + pk + '/';

            $.ajax({
                type: 'POST',
                url: url,
                dataType: 'json',
                async: true,
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    pk: pk,
                },
                success: function(json) {

                }
            });

            $('button#good').addClass('btn-success');
            $('button#help').removeClass('btn-warning').addClass('btn-default');
            $('button#trouble').removeClass('btn-danger').addClass('btn-default');

        });



        $('button#help').click(function() {

            var pk = $(this).data('task-id');
            var url = '/update-task-help/' + pk + '/';

            $.ajax({
                type: 'POST',
                url: url,
                dataType: 'json',
                async: true,
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    pk: pk,
                },
                success: function(json) {

                }
            });

            $('button#good').removeClass('btn-success').addClass('btn-default');
            $('button#help').addClass('btn-warning');
            $('button#trouble').removeClass('btn-danger').addClass('btn-default');

        });




        $('button#trouble').click(function() {

            var pk = $(this).data('task-id');
            var url = '/update-task-trouble/' + pk + '/';

            $.ajax({
                type: 'POST',
                url: url,
                dataType: 'json',
                async: true,
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    pk: pk,
                },
                success: function(json) {

                }
            });


            $('button#good').removeClass('btn-success').addClass('btn-default');
            $('button#help').removeClass('btn-warning').addClass('btn-default');
            $('button#trouble').addClass('btn-danger');

        });

    </script>

{% endblock %}